<template>
  <div>
    <NuxtRouteAnnouncer />

    <h1>Subscription management interface</h1>

    <h2>Email addresses</h2>

    <DataTable
      caption="Individual addresses"
      captionClass="text-xl font-bold text-left"
      :columns="{
        address: 'Address',
        verified: 'Verified',
        'plus-notation': '+ Notation',
        receive: 'Receive',
        duplicates: 'Duplicates'
      }"
      :rows="[
        {
          address: 'name@example.com',
          verified: true,
          'plus-notation': false,
          receive: true,
          duplicates: false
        },
        {
          address: 'othername@otherdomain.org',
          verified: false,
          'plus-notation': false,
          receive: true,
          duplicates: false
        }
      ]"
      :cell-formatters="{
        verified: (val) => h(Badge, val)
      }"
      :sortableColumns="['address']"
      :sort="{
        address: (addressA, addressB) => addressA.localeCompare(addressB)
      }"
    >
      <template #tfoot="{ colSpanAll }">
        <tr>
          <td :colspan="colSpanAll">
            <button type="button">add</button>
          </td>
        </tr>
      </template>
    </DataTable>

    <DataTable
      caption="Private domains"
      captionClass="text-xl font-bold text-left"
      :columns="{
        address: 'Address',
        verified: 'Verified',
        txt: 'TXT',
        pattern: 'Pattern'
      }"
      :rows="[
        {
          address: 'name@example.com',
          verified: true,
          txt: false,
          pattern: 'ietf-<list-name>@mydomain.tld'
        }
      ]"
      :cell-formatters="{
        verified: (val) => h(Badge, val)
      }"
      :sortableColumns="['address']"
      :sort="{
        address: (addressA, addressB) => addressA.localeCompare(addressB)
      }"
    >
      <template #tfoot="{ colSpanAll }">
        <tr>
          <td :colspan="colSpanAll">
            <button type="button">add</button>
          </td>
        </tr>
      </template>
    </DataTable>

    <div class="flex items-center gap-2">
      <label>Default address:</label>
      <input
        type="email"
        value="name@example.com"
        class="border border-black p-2"
      />
    </div>
    <div class="flex items-center gap-2">
      <label>Pause mail delivery to all addresses:</label>
      <HeadlessSwitch
        v-model="enabled"
        :class="enabled ? 'bg-blue-600' : 'bg-gray-200'"
        class="relative inline-flex h-6 w-11 items-center rounded-full"
      >
        <span class="sr-only">Enable notifications</span>
        <span
          :class="enabled ? 'translate-x-6' : 'translate-x-1'"
          class="inline-block h-4 w-4 transform rounded-full bg-white transition"
        />
      </HeadlessSwitch>
    </div>

    <h2>Subscriptions</h2>

    <fieldset>
      <legend>Important news</legend>
      <p id="important-intro">
        This is a very low volume list with only the most important stuff sent
        to it. We ask all IETF participants to please subscribe to this list.
      </p>
      <div>
        <label>
          <input type="checkbox" aria-describedby="important-intro" />
          Subscribe to important news
        </label>
        <div>4/1/1 (?)</div>
        <select>
          <option value="">email address 1 from table above</option>
        </select>
        <label>
          <input type="checkbox" />
          Digest
        </label>
      </div>
    </fieldset>

    <fieldset>
      <legend>Direct survey opt-out</legend>
      <p id="opt-out-intro">
        Occasionally a custom list of addresses is assembled and those are
        contacted directly with a survey request. If you do not want to receive
        direct survey requests then you are opt-out below. This will not stop
        you receiving a survey sent to a list that you are subscribed to.
      </p>
      <label>
        <input type="checkbox" aria-describedby="important-intro" />
        Opt-out of direct survey requests
      </label>
    </fieldset>

    <h3>Announcements</h3>
    <p>
      One-way announcement lists. Some are automatically generated by
      Datatracker while others are manual. The two categories are Technical and
      Administrative.
    </p>

    <DataTable
      :columns="{
        description: 'Description',
        volume: 'Volume (?)',
        address: 'Address',
        digest: 'Digest (?)'
      }"
      :rows="[
        {
          description: {
            id: 'new-rfc-announce',
            title: 'New RFCs'
          },
          volume: '41/16/1',
          address: '(default address)',
          digest: false
        },
        {
          description: {
            id: 'wg-announce',
            title: 'New WG charters and WG closures'
          },
          volume: '41/16/1',
          address: '(default address)',
          digest: true
        },
        {
          description: {
            id: 'last-call',
            title: 'Last calls'
          },
          volume: '41/16/1',
          address: '(default address)',
          digest: true
        },
        {
          description: {
            id: 'interim-announce',
            title: 'Interim meetings'
          },
          volume: '41/16/1',
          address: '(default address)',
          digest: true
        },
        {
          description: {
            id: 'document-actions',
            title: 'Document actions'
          },
          volume: '41/16/1',
          address: '(default address)',
          digest: true
        },
        {
          description: {
            id: 'conflict-reviews',
            title: 'IESG conflict review results'
          },
          volume: '41/16/1',
          address: '(default address)',
          digest: true
        }
      ]"
      :cell-formatters="{
        description: (val) => `${val.id} - ${val.title}`
      }"
      :sortableColumns="['description']"
      :sort="{
        description: (descriptionA, descriptionB) =>
          descriptionA.id.localeCompare(descriptionB.id)
      }"
    >
    </DataTable>

    <DataTable
      :columns="{
        name: formattedColumnName,
        body: 'Content'
      }"
      :rows="[
        { name: 'Jeff', body: ['sdf'] },
        { name: 'Kevin', body: [0] },
        { name: 'Bob', body: false }
      ]"
      :cell-formatters="{
        body: (val) => {
          if (typeof val === 'boolean') {
            return `FORMATTED [${val.toString()}]`
          }
          return `FORMATTED [${val.join('|')}]`
        },
        name: (val) => {
          return h('h1', val)
        }
      }"
      :sortable-columns="['body']"
      :row-link="
        (row) => {
          return h('a', {
            class: 'absolute inset-0',
            href: `/fdf/${row.body}/`
          })
        }
      "
    />
  </div>
</template>
<script setup lang="ts">
provideHeadlessUseId(() => useId())
import Badge from './components/Badge.vue'
const formattedColumnName = h('b', 'My id')
const enabled = ref(false)
</script>
